name: Pack
on:
    release:
      types: [published]
jobs:
    pack-on-release:
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
            uses: actions/checkout@v2  
          - name: Pack
            working-directory: ./Vorn.Hub
            run: dotnet pack --configuration Release  --output .
          - name: Push
            working-directory: ./Vorn.Hub
            run: dotnet nuget push Vorn.Hub.*.nupkg --source https://nuget.pkg.github.com/VORNIR/index.json --api-key ${{ secrets.ACCESSTOKEN }}
